title: Olamilekan Yusuf
logo: /assets/img/headshot_circle.png
description: Welcome to my Academic portfolio
#show_downloads: true
author:
  email: horlamilekanyusuf@gmail.com
theme: jekyll-theme-minimal
